### ISSUE TITLE
`GroupBy`的示例，运行结果和实际情况不一样

### ISSUE THREAD

**Issue by jixingcn** [darjun/darjun.github.io#2]
为什么会有`item: 10`？

https://github.com/darjun/darjun.github.io/blob/0322ec507ff40ec1831aaaa0ee2bfed0468e40a2/2020/10/11/godailylib/rxgo/index.html#L1592

**Comment by darjun** [comment]
我再次运行了，结果确实是有 item：10 的，我去看了一下源码，在描述上应该是不包括的，但是实现上又包括了，我用的是v2.2.0版本。然后去看了提交记录，在新版本中已经修复了：
<img width="730" alt="截屏2021-07-26 上午10 23 34" src="https://user-images.githubusercontent.com/18298106/126924660-5f3ba0c9-289c-4d81-a147-7fed762b5f39.png">

@jixingcn  感谢指出
